import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://swwcblmsymbwshsxqhag.supabase.co',
  process.env.SUPABASE_SERVICE_ROLE_KEY || 'YOUR_SUPABASE_SERVICE_ROLE_KEY'
);

const services = [
  { slug: 'web-mobile', title: 'Web & Mobile Development', tagline: 'Full-stack products built to scale from day one.', color: '#818cf8', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=1200', video: 'https://www.w3schools.com/html/mov_bbb.mp4', description: 'We design and engineer web applications and native mobile experiences that are fast, accessible, and beautifully crafted. From SaaS platforms to consumer apps.', content: '<h2>Beyond the Framework</h2><p>Building for the modern web requires more than just knowing React.</p>', tech: ['React', 'Next.js', 'React Native', 'TypeScript', 'Node.js'], featured: true },
  { slug: 'ai-ml', title: 'AI & Machine Learning', tagline: 'Intelligence woven into the fabric of your product.', color: '#a78bfa', image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=1200', description: 'LLM integrations, computer vision, NLP, predictive analytics, and custom model development.', content: '<h2>Production AI</h2><p>We take ML models out of the Jupyter notebook and deploy them into hardened production pipelines.</p>', tech: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI', 'LangChain'], featured: true },
  { slug: 'cloud-devops', title: 'Cloud & DevOps', tagline: 'Resilient infrastructure that scales without friction.', color: '#60a5fa', image: 'https://images.unsplash.com/photo-1667372283536-a831e58cddef?auto=format&fit=crop&q=80&w=1200', description: 'Cloud architecture, CI/CD pipelines, Kubernetes orchestration, and platform engineering.', content: '<h2>Infrastructure as Code</h2><p>Everything we build is defined in Terraform and automated via GitHub Actions.</p>', tech: ['AWS', 'GCP', 'Kubernetes', 'Terraform', 'GitHub Actions'], featured: true },
  { slug: 'embedded', title: 'Embedded Systems', tagline: 'Software that runs where others cannot reach.', color: '#34d399', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200', description: 'Firmware, RTOS, IoT platforms, and hardware-software co-design.', content: '<h2>Safety Critical</h2><p>Our firmware engineers specialise in Rust and C++ for mission-critical embedded systems.</p>', tech: ['C/C++', 'Rust', 'RTOS', 'ARM', 'RISC-V'], featured: false },
  { slug: 'cybersecurity', title: 'Cybersecurity', tagline: 'Zero-trust architecture, pen-testing, and compliance.', color: '#f87171', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200', description: 'From penetration testing to secure-by-design architecture.', content: '<h2>Secure by Design</h2><p>We bake security into the CI/CD pipeline from day one.</p>', tech: ['OWASP', 'ISO 27001', 'NDPR', 'Zero Trust', 'SIEM'], featured: false },
  { slug: 'data-engineering', title: 'Data Engineering', tagline: 'Reliable data pipelines from raw bytes to business insight.', color: '#fbbf24', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1200', description: 'Data lake architecture, real-time streaming, ETL pipelines.', content: '<h2>Data that Flows</h2><p>We build robust ETL pipelines that process terabytes of data daily.</p>', tech: ['Spark', 'Kafka', 'dbt', 'Snowflake', 'Airflow'], featured: false },
  { slug: 'blockchain', title: 'Blockchain & Web3', tagline: 'Smart contracts, DeFi protocols, and NFT infrastructure.', color: '#c084fc', image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=1200', description: 'Ethereum, Solana, and multi-chain development.', content: '<h2>Audited Smart Contracts</h2><p>Our Web3 infrastructure powers hundreds of millions in TVL.</p>', tech: ['Solidity', 'Rust', 'Hardhat', 'The Graph', 'IPFS'], featured: false },
  { slug: 'design-systems', title: 'Design Systems & UX', tagline: 'Cohesive, accessible interfaces at any scale.', color: '#fb923c', image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=1200', description: 'Component libraries, design tokens, accessibility audits.', content: '<h2>Tokens and Components</h2><p>We build design systems that engineers actually want to adopt.</p>', tech: ['Figma', 'Storybook', 'WCAG', 'React', 'CSS-in-JS'], featured: false },
];

const portfolio = [
  { slug: 'nexus-health', title: 'Nexus Health Platform', client: 'NexusHealth Ltd.', industry: 'Healthcare', color: '#34d399', summary: 'End-to-end EHR platform serving 1.2M patients across 40 hospitals.', content: '<h2>The Challenge</h2><p>NexusHealth needed to replace a fragmented legacy EHR system.</p>', tech: ['React', 'Python', 'PostgreSQL', 'AWS', 'TensorFlow'], results: [{ metric: '1.2M', label: 'Active Patients' }, { metric: '94%', label: 'AI Accuracy' }, { metric: '68%', label: 'Admin Reduction' }], featured: true },
  { slug: 'orbital-fintech', title: 'Orbital Trading Engine', client: 'Orbital Capital Group', industry: 'FinTech', color: '#818cf8', summary: 'Ultra-low-latency algorithmic trading infrastructure processing 2M transactions per second.', content: '<h2>High Frequency Scale</h2><p>Rewriting the trading engine in Rust allowed Orbital Capital to handle 2 million transactions per second.</p>', tech: ['Rust', 'C++', 'Redis', 'Kafka', 'FIX Protocol'], results: [{ metric: '2M/s', label: 'Transactions' }, { metric: '<1ms', label: 'Execution' }, { metric: '99.999%', label: 'Uptime' }], featured: true },
  { slug: 'aurora-logistics', title: 'Aurora Fleet Intelligence', client: 'Aurora Logistics GmbH', industry: 'Logistics', color: '#60a5fa', summary: 'AI-powered route optimisation for 4,200 vehicles across 18 countries.', content: '<h2>Global Route Optimisation</h2><p>Using real-time traffic data and a custom Graph Neural Network.</p>', tech: ['Python', 'React Native', 'PostgreSQL', 'Kubernetes', 'GraphQL'], results: [{ metric: '23%', label: 'Fuel Savings' }, { metric: '31%', label: 'CO2 Reduced' }, { metric: '4,200', label: 'Vehicles' }], featured: true },
  { slug: 'zenith-manufacturing', title: 'Zenith Smart Factory OS', client: 'Zenith Manufacturing PLC', industry: 'Manufacturing', color: '#fbbf24', summary: 'Industrial IoT platform connecting 3,400 sensors across 12 production lines.', content: '<h2>Industrial IoT</h2><p>Connected sensors stream 1TB of data daily.</p>', tech: ['Rust', 'MQTT', 'InfluxDB', 'React', 'Kubernetes'], results: [{ metric: '78%', label: 'Less Downtime' }, { metric: '3,400', label: 'Sensors' }, { metric: 'N3B', label: 'Annual Savings' }], featured: false },
  { slug: 'prism-edtech', title: 'Prism Learning Platform', client: 'Prism EdTech Inc.', industry: 'Education', color: '#c084fc', summary: 'Adaptive AI tutoring platform used by 280,000 students across 60 universities.', content: '<h2>Adaptive Learning Paths</h2><p>We built a PyTorch model that dynamically adjusts the curriculum.</p>', tech: ['Next.js', 'Python', 'PyTorch', 'AWS', 'PostgreSQL'], results: [{ metric: '280K', label: 'Students' }, { metric: '+34%', label: 'Pass Rates' }, { metric: '60', label: 'Universities' }], featured: false },
  { slug: 'vaultchain', title: 'VaultChain DeFi Protocol', client: 'VaultChain Labs', industry: 'Web3', color: '#f87171', summary: 'Multi-chain DeFi protocol managing $340M TVL.', content: '<h2>Bulletproof Infrastructure</h2><p>Managing $340M TVL requires zero compromise.</p>', tech: ['Solidity', 'Rust', 'The Graph', 'Hardhat', 'IPFS'], results: [{ metric: '$340M', label: 'TVL' }, { metric: '0', label: 'Security Incidents' }, { metric: '180K', label: 'Wallet Users' }], featured: false },
];

const blogPosts = [
  { slug: 'llm-production-systems', title: 'Engineering LLMs for Production: Lessons from 18 Months in the Field', excerpt: 'Context windows, hallucination mitigation, cost optimisation.', category: 'AI Engineering', author: 'Dr. Amara Osei', author_initials: 'AO', date: 'June 28, 2025', read_time: '12 min read', tags: ['LLM', 'Production', 'MLOps'], image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=1200', content: '<h2>The Operational Reality</h2><p>Deploying LLMs into production requires a massive shift.</p>', featured: true },
  { slug: 'rust-embedded-systems', title: 'Why We Switched from C++ to Rust for Safety-Critical Embedded Firmware', excerpt: 'Memory safety guarantees, zero-cost abstractions.', category: 'Embedded Systems', author: 'Marcus Chen', author_initials: 'MC', date: 'June 14, 2025', read_time: '9 min read', tags: ['Rust', 'Embedded', 'Safety'], image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200', content: '<h2>The Cost of Memory Un-Safety</h2><p>In safety-critical systems, a segmentation fault isnt just an inconvenience.</p>', featured: true },
  { slug: 'kubernetes-cost-optimisation', title: 'Cutting Our Kubernetes Cloud Bill by 58%', excerpt: 'Pod autoscaling, spot instances, cluster bin-packing.', category: 'Cloud & DevOps', author: 'Sophia Andersen', author_initials: 'SA', date: 'May 30, 2025', read_time: '15 min read', tags: ['Kubernetes', 'AWS', 'Cost'], image: 'https://images.unsplash.com/photo-1667372283536-a831e58cddef?auto=format&fit=crop&q=80&w=1200', content: '<h2>Infrastructure as Cost</h2><p>Cloud spend is engineering spend.</p>', featured: false },
  { slug: 'zero-trust-architecture', title: 'Implementing Zero Trust: From Theory to Production in 90 Days', excerpt: 'Step-by-step guide to deploying a zero-trust network architecture.', category: 'Cybersecurity', author: 'James Okafor', author_initials: 'JO', date: 'May 12, 2025', read_time: '11 min read', tags: ['Security', 'Zero Trust', 'Architecture'], image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200', content: '<h2>Verify Everything</h2><p>Zero trust isnt a product you buy.</p>', featured: false },
  { slug: 'design-system-scale', title: 'Building a Design System That Actually Gets Adopted', excerpt: 'Token architecture, component governance, documentation strategies.', category: 'Design Engineering', author: 'Priya Mehta', author_initials: 'PM', date: 'April 28, 2025', read_time: '8 min read', tags: ['Design Systems', 'UX', 'Frontend'], image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=1200', content: '<h2>Tokens are Just the Beginning</h2><p>A design system without adoption is just an expensive UI kit.</p>', featured: false },
  { slug: 'data-mesh-healthcare', title: 'Data Mesh Architecture in Healthcare', excerpt: 'Federated data platform for a major hospital group.', category: 'Data Engineering', author: 'Dr. Amara Osei', author_initials: 'AO', date: 'April 10, 2025', read_time: '14 min read', tags: ['Data Mesh', 'Healthcare', 'NDPR'], image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1200', content: '<h2>Federated Responsibility</h2><p>Centralised data lakes become bottlenecks.</p>', featured: false },
];

async function seed() {
  const { error: e1 } = await supabase.from('services').upsert(services, { onConflict: 'slug' });
  if (e1) console.error('services error:', e1.message); else console.log('services seeded');

  const { error: e2 } = await supabase.from('portfolio').upsert(portfolio, { onConflict: 'slug' });
  if (e2) console.error('portfolio error:', e2.message); else console.log('portfolio seeded');

  const { error: e3 } = await supabase.from('blog_posts').upsert(blogPosts, { onConflict: 'slug' });
  if (e3) console.error('blog_posts error:', e3.message); else console.log('blog_posts seeded');

  console.log('Seed complete');
}

seed();
