-- ============================================================
-- SCHEMA MIGRATIONS
-- ============================================================
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verified boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS can_verify boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS can_manage_instructors boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS can_manage_admins boolean DEFAULT false;

-- ============================================================
-- SEED: Admin Profile
-- ============================================================
INSERT INTO profiles (id, name, avatar, role, email, verified, can_verify, can_manage_instructors, can_manage_admins)
VALUES ('00000000-0000-0000-0000-000000000001', 'Admin', 'https://api.dicebear.com/7.x/initials/svg?seed=Admin&backgroundColor=10b981', 'admin', 'admin@seed.software', true, true, true, true)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, avatar=EXCLUDED.avatar, role=EXCLUDED.role, email=EXCLUDED.email,
  verified=EXCLUDED.verified, can_verify=EXCLUDED.can_verify,
  can_manage_instructors=EXCLUDED.can_manage_instructors, can_manage_admins=EXCLUDED.can_manage_admins;

-- ============================================================
-- SEED: Services
-- ============================================================
INSERT INTO services (slug, title, tagline, color, image, video, description, content, tech, featured) VALUES
('web-mobile', 'Web & Mobile Development', 'Full-stack products built to scale from day one.', '#818cf8', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=1200', 'https://www.w3schools.com/html/mov_bbb.mp4', 'We design and engineer web applications and native mobile experiences that are fast, accessible, and beautifully crafted.', '<h2>Beyond the Framework</h2><p>Building for the modern web requires more than just knowing React.</p>', ARRAY['React','Next.js','React Native','TypeScript','Node.js'], true),
('ai-ml', 'AI & Machine Learning', 'Intelligence woven into the fabric of your product.', '#a78bfa', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=1200', NULL, 'LLM integrations, computer vision, NLP, predictive analytics, and custom model development.', '<h2>Production AI</h2><p>We take ML models out of the Jupyter notebook and deploy them into hardened production pipelines.</p>', ARRAY['Python','TensorFlow','PyTorch','OpenAI','LangChain'], true),
('cloud-devops', 'Cloud & DevOps', 'Resilient infrastructure that scales without friction.', '#60a5fa', 'https://images.unsplash.com/photo-1667372283536-a831e58cddef?auto=format&fit=crop&q=80&w=1200', NULL, 'Cloud architecture, CI/CD pipelines, Kubernetes orchestration, and platform engineering.', '<h2>Infrastructure as Code</h2><p>Everything we build is defined in Terraform and automated via GitHub Actions.</p>', ARRAY['AWS','GCP','Kubernetes','Terraform','GitHub Actions'], true),
('embedded', 'Embedded Systems', 'Software that runs where others cannot reach.', '#34d399', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200', NULL, 'Firmware, RTOS, IoT platforms, and hardware-software co-design.', '<h2>Safety Critical</h2><p>Our firmware engineers specialise in Rust and C++ for mission-critical embedded systems.</p>', ARRAY['C/C++','Rust','RTOS','ARM','RISC-V'], false),
('cybersecurity', 'Cybersecurity', 'Zero-trust architecture, pen-testing, and compliance.', '#f87171', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200', NULL, 'From penetration testing to secure-by-design architecture.', '<h2>Secure by Design</h2><p>We bake security into the CI/CD pipeline from day one.</p>', ARRAY['OWASP','ISO 27001','NDPR','Zero Trust','SIEM'], false),
('data-engineering', 'Data Engineering', 'Reliable data pipelines from raw bytes to business insight.', '#fbbf24', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1200', NULL, 'Data lake architecture, real-time streaming, ETL pipelines.', '<h2>Data that Flows</h2><p>We build robust ETL pipelines that process terabytes of data daily.</p>', ARRAY['Spark','Kafka','dbt','Snowflake','Airflow'], false),
('blockchain', 'Blockchain & Web3', 'Smart contracts, DeFi protocols, and NFT infrastructure.', '#c084fc', 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=1200', NULL, 'Ethereum, Solana, and multi-chain development.', '<h2>Audited Smart Contracts</h2><p>Our Web3 infrastructure powers hundreds of millions in TVL.</p>', ARRAY['Solidity','Rust','Hardhat','The Graph','IPFS'], false),
('design-systems', 'Design Systems & UX', 'Cohesive, accessible interfaces at any scale.', '#fb923c', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=1200', NULL, 'Component libraries, design tokens, accessibility audits.', '<h2>Tokens and Components</h2><p>We build design systems that engineers actually want to adopt.</p>', ARRAY['Figma','Storybook','WCAG','React','CSS-in-JS'], false)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, tagline=EXCLUDED.tagline, color=EXCLUDED.color, image=EXCLUDED.image, video=EXCLUDED.video, description=EXCLUDED.description, content=EXCLUDED.content, tech=EXCLUDED.tech, featured=EXCLUDED.featured;

-- ============================================================
-- SEED: Portfolio
-- ============================================================
INSERT INTO portfolio (slug, title, client, industry, color, summary, content, tech, results, featured) VALUES
('nexus-health', 'Nexus Health Platform', 'NexusHealth Ltd.', 'Healthcare', '#34d399', 'End-to-end EHR platform serving 1.2M patients across 40 hospitals.', '<h2>The Challenge</h2><p>NexusHealth needed to replace a fragmented legacy EHR system.</p>', ARRAY['React','Python','PostgreSQL','AWS','TensorFlow'], '[{"metric":"1.2M","label":"Active Patients"},{"metric":"94%","label":"AI Accuracy"},{"metric":"68%","label":"Admin Reduction"}]', true),
('orbital-fintech', 'Orbital Trading Engine', 'Orbital Capital Group', 'FinTech', '#818cf8', 'Ultra-low-latency algorithmic trading infrastructure processing 2M transactions per second.', '<h2>High Frequency Scale</h2><p>Rewriting the trading engine in Rust allowed Orbital Capital to handle 2 million transactions per second.</p>', ARRAY['Rust','C++','Redis','Kafka','FIX Protocol'], '[{"metric":"2M/s","label":"Transactions"},{"metric":"<1ms","label":"Execution"},{"metric":"99.999%","label":"Uptime"}]', true),
('aurora-logistics', 'Aurora Fleet Intelligence', 'Aurora Logistics GmbH', 'Logistics', '#60a5fa', 'AI-powered route optimisation for 4,200 vehicles across 18 countries.', '<h2>Global Route Optimisation</h2><p>Using real-time traffic data and a custom Graph Neural Network.</p>', ARRAY['Python','React Native','PostgreSQL','Kubernetes','GraphQL'], '[{"metric":"23%","label":"Fuel Savings"},{"metric":"31%","label":"CO2 Reduced"},{"metric":"4,200","label":"Vehicles"}]', true),
('zenith-manufacturing', 'Zenith Smart Factory OS', 'Zenith Manufacturing PLC', 'Manufacturing', '#fbbf24', 'Industrial IoT platform connecting 3,400 sensors across 12 production lines.', '<h2>Industrial IoT</h2><p>Connected sensors stream 1TB of data daily.</p>', ARRAY['Rust','MQTT','InfluxDB','React','Kubernetes'], '[{"metric":"78%","label":"Less Downtime"},{"metric":"3,400","label":"Sensors"},{"metric":"N3B","label":"Annual Savings"}]', false),
('prism-edtech', 'Prism Learning Platform', 'Prism EdTech Inc.', 'Education', '#c084fc', 'Adaptive AI tutoring platform used by 280,000 students across 60 universities.', '<h2>Adaptive Learning Paths</h2><p>We built a PyTorch model that dynamically adjusts the curriculum.</p>', ARRAY['Next.js','Python','PyTorch','AWS','PostgreSQL'], '[{"metric":"280K","label":"Students"},{"metric":"+34%","label":"Pass Rates"},{"metric":"60","label":"Universities"}]', false),
('vaultchain', 'VaultChain DeFi Protocol', 'VaultChain Labs', 'Web3', '#f87171', 'Multi-chain DeFi protocol managing $340M TVL.', '<h2>Bulletproof Infrastructure</h2><p>Managing $340M TVL requires zero compromise.</p>', ARRAY['Solidity','Rust','The Graph','Hardhat','IPFS'], '[{"metric":"$340M","label":"TVL"},{"metric":"0","label":"Security Incidents"},{"metric":"180K","label":"Wallet Users"}]', false)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, client=EXCLUDED.client, industry=EXCLUDED.industry, color=EXCLUDED.color, summary=EXCLUDED.summary, content=EXCLUDED.content, tech=EXCLUDED.tech, results=EXCLUDED.results, featured=EXCLUDED.featured;

-- ============================================================
-- SEED: Blog Posts
-- ============================================================
INSERT INTO blog_posts (slug, title, excerpt, category, author, author_initials, date, read_time, tags, image, content, featured) VALUES
('llm-production-systems', 'Engineering LLMs for Production: Lessons from 18 Months in the Field', 'Context windows, hallucination mitigation, cost optimisation.', 'AI Engineering', 'Dr. Amara Osei', 'AO', 'June 28, 2025', '12 min read', ARRAY['LLM','Production','MLOps'], 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=1200', '<h2>The Operational Reality</h2><p>Deploying LLMs into production requires a massive shift.</p>', true),
('rust-embedded-systems', 'Why We Switched from C++ to Rust for Safety-Critical Embedded Firmware', 'Memory safety guarantees, zero-cost abstractions.', 'Embedded Systems', 'Marcus Chen', 'MC', 'June 14, 2025', '9 min read', ARRAY['Rust','Embedded','Safety'], 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200', '<h2>The Cost of Memory Un-Safety</h2><p>In safety-critical systems, a segfault isnt just an inconvenience.</p>', true),
('kubernetes-cost-optimisation', 'Cutting Our Kubernetes Cloud Bill by 58%', 'Pod autoscaling, spot instances, cluster bin-packing.', 'Cloud & DevOps', 'Sophia Andersen', 'SA', 'May 30, 2025', '15 min read', ARRAY['Kubernetes','AWS','Cost'], 'https://images.unsplash.com/photo-1667372283536-a831e58cddef?auto=format&fit=crop&q=80&w=1200', '<h2>Infrastructure as Cost</h2><p>Cloud spend is engineering spend.</p>', false),
('zero-trust-architecture', 'Implementing Zero Trust: From Theory to Production in 90 Days', 'Step-by-step guide to deploying a zero-trust network architecture.', 'Cybersecurity', 'James Okafor', 'JO', 'May 12, 2025', '11 min read', ARRAY['Security','Zero Trust','Architecture'], 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200', '<h2>Verify Everything</h2><p>Zero trust isnt a product you buy.</p>', false),
('design-system-scale', 'Building a Design System That Actually Gets Adopted', 'Token architecture, component governance, documentation strategies.', 'Design Engineering', 'Priya Mehta', 'PM', 'April 28, 2025', '8 min read', ARRAY['Design Systems','UX','Frontend'], 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=1200', '<h2>Tokens are Just the Beginning</h2><p>A design system without adoption is just an expensive UI kit.</p>', false),
('data-mesh-healthcare', 'Data Mesh Architecture in Healthcare', 'Federated data platform for a major hospital group.', 'Data Engineering', 'Dr. Amara Osei', 'AO', 'April 10, 2025', '14 min read', ARRAY['Data Mesh','Healthcare','NDPR'], 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1200', '<h2>Federated Responsibility</h2><p>Centralised data lakes become bottlenecks.</p>', false)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, excerpt=EXCLUDED.excerpt, category=EXCLUDED.category, author=EXCLUDED.author, author_initials=EXCLUDED.author_initials, date=EXCLUDED.date, read_time=EXCLUDED.read_time, tags=EXCLUDED.tags, image=EXCLUDED.image, content=EXCLUDED.content, featured=EXCLUDED.featured;

-- ============================================================
-- SEED: Courses
-- ============================================================
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('react-masterclass','React & Next.js Masterclass','From components to production deployment in 6 weeks.','A comprehensive deep-dive into modern React development. Covering hooks, state management, server-side rendering, and full-stack architecture with Next.js.','Intermediate','8 hours 45 min total','Self-paced + Weekly Q&A','Priya Sharma','VP Cloud Engineering',ARRAY['Components & Hooks','State Management','SSR & SSG','Routing & Navigation','API Integration','Testing','Deployment','Performance'],6,1200,'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=1200','<h2>What You''ll Learn</h2><p>This masterclass takes you from intermediate React knowledge to production-ready mastery.</p>','[{"id":"1","title":"React Foundations & JSX Deep Dive","duration":"1 hour 15 min","content":"<h2>Understanding JSX at the Compiler Level</h2><p>JSX is syntactic sugar for React.createElement calls.</p>"},{"id":"2","title":"Hooks: useState, useEffect & Custom Hooks","duration":"1 hour 30 min","content":"<h2>The Mental Model of Hooks</h2><p>Hooks let you use state and other React features without writing a class.</p>"},{"id":"3","title":"State Management Patterns","duration":"1 hour 20 min","content":"<h2>Lifting State, Context & Beyond</h2><p>State management is about answering one question: where does each piece of state live?</p>"},{"id":"4","title":"Next.js & Server Components","duration":"1 hour 45 min","content":"<h2>Full-Stack React with Next.js</h2><p>Next.js extends React with server-side rendering, static generation, and API routes.</p>"},{"id":"5","title":"Data Fetching & Authentication","duration":"1 hour 10 min","content":"<h2>Fetching Data in Next.js</h2><p>Next.js introduces four data fetching patterns: static, dynamic, incremental, and client-side.</p>"},{"id":"6","title":"Testing & Deployment","duration":"1 hour 25 min","content":"<h2>Shipping with Confidence</h2><p>A solid testing strategy prevents regressions.</p>"}]'::jsonb,true) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('python-data-science','Python for Data Science','Turn raw data into actionable insights.','A beginner-friendly introduction to data science using Python. Learn pandas, numpy, matplotlib, and scikit-learn through hands-on projects.','Beginner','5 hours total','Self-paced + Mentor Support','Dr. Aisha Nkosi','CEO & Co-Founder',ARRAY['Python Basics','NumPy & Pandas','Data Visualization','Statistical Analysis','Machine Learning Basics'],5,2300,'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200','<h2>From Zero to Data-Driven</h2><p>Data is everywhere, but extracting value from it requires the right tools and mindset.</p>','[{"id":"1","title":"Python Fundamentals for Data","duration":"1 hour","content":"<h2>Python for Data Work</h2><p>Before diving into libraries, you need solid Python fundamentals with a data twist.</p>"},{"id":"2","title":"NumPy & Vectorisation","duration":"1 hour 10 min","content":"<h2>Fast Numerical Computing</h2><p>NumPy is the foundation of the Python data stack.</p>"},{"id":"3","title":"Pandas for Data Wrangling","duration":"1 hour 20 min","content":"<h2>DataFrames: The Workhorse</h2><p>Pandas DataFrames are the Excel spreadsheets of the programming world.</p>"},{"id":"4","title":"Visualisation with Matplotlib & Seaborn","duration":"1 hour","content":"<h2>Tell a Story with Data</h2><p>A great chart communicates insights instantly.</p>"},{"id":"5","title":"Intro to Machine Learning with scikit-learn","duration":"1 hour 10 min","content":"<h2>Your First Models</h2><p>Train your first classification and regression models.</p>"}]'::jsonb,true) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('node-js-backend','Node.js Backend Development','Build scalable APIs and backend services.','Learn to design, build, and deploy robust backend systems using Node.js, Express, and PostgreSQL.','Intermediate','7 hours 15 min total','Self-paced + Weekly Q&A','Thomas Ekwe','VP Engineering',ARRAY['Express.js','REST API Design','Database Design','Authentication','Testing','Deployment'],5,1800,'https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&q=80&w=1200','<h2>Backend Engineering, Properly</h2><p>This course covers everything you need to build production-grade backend systems.</p>','[{"id":"1","title":"Express.js & Middleware Architecture","duration":"1 hour 30 min","content":"<h2>Understanding the Middleware Stack</h2><p>Express is fundamentally a middleware runner.</p>"},{"id":"2","title":"RESTful API Design Principles","duration":"1 hour 15 min","content":"<h2>Designing APIs That Last</h2><p>A well-designed API outlives any single implementation.</p>"},{"id":"3","title":"Database Design & PostgreSQL","duration":"1 hour 45 min","content":"<h2>Data Integrity at Scale</h2><p>PostgreSQL is the gold standard for relational databases.</p>"},{"id":"4","title":"Authentication & Authorisation","duration":"1 hour 30 min","content":"<h2>Securing Your API</h2><p>Implement JWT-based authentication with refresh token rotation.</p>"},{"id":"5","title":"Testing & Deployment","duration":"1 hour 15 min","content":"<h2>Shipping Reliable Backends</h2><p>Integration tests, database fixtures, CI/CD pipelines.</p>"}]'::jsonb,false) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('docker-kubernetes','Docker & Kubernetes in Production','Container orchestration for real-world systems.','Master containerisation and orchestration. From Dockerfiles to multi-cluster Kubernetes deployments.','Intermediate','8 hours 45 min total','Self-paced + Labs','Priya Sharma','VP Cloud Engineering',ARRAY['Docker','Kubernetes Basics','Pods & Deployments','Services & Networking','Storage & Config','Monitoring & Logging'],5,950,'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&q=80&w=1200','<h2>Containers at Scale</h2><p>Docker changed how we package software. Kubernetes changed how we run it.</p>','[{"id":"1","title":"Docker Deep Dive","duration":"1 hour 30 min","content":"<h2>Beyond docker run</h2><p>Understand layers, caching, multi-stage builds.</p>"},{"id":"2","title":"Kubernetes Architecture","duration":"1 hour 45 min","content":"<h2>Control Planes & Nodes</h2><p>Understand the components that make Kubernetes tick.</p>"},{"id":"3","title":"Pods, Deployments & Services","duration":"2 hours","content":"<h2>Running Workloads</h2><p>Pods, Deployments, and Services - the three core primitives.</p>"},{"id":"4","title":"ConfigMaps, Secrets & Storage","duration":"1 hour 30 min","content":"<h2>Configuration Management</h2><p>Managing config and secrets properly in Kubernetes.</p>"},{"id":"5","title":"Monitoring, Logging & Scaling","duration":"2 hours","content":"<h2>Production Operations</h2><p>HPA, Prometheus, structured logging, and alerting.</p>"}]'::jsonb,true) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('rust-fundamentals','Rust Systems Programming','Safe, fast, and fearless systems-level development.','An intensive deep-dive into Rust programming. Ownership, borrowing, lifetimes, concurrency, and unsafe Rust.','Advanced','9 hours total','Self-paced + Code Reviews','Marcus Chen','Head of Robotics',ARRAY['Ownership & Borrowing','Lifetimes','Traits & Generics','Concurrency','Unsafe Rust','FFI & Embedded'],5,680,'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?auto=format&fit=crop&q=80&w=1200','<h2>Fearless Concurrency, Zero Cost Abstractions</h2><p>Rust is transforming systems programming.</p>','[{"id":"1","title":"Ownership & Borrowing","duration":"2 hours","content":"<h2>The Core of Rust</h2><p>Ownership is Rust''s most unique feature.</p>"},{"id":"2","title":"Lifetimes","duration":"1 hour 45 min","content":"<h2>Ensuring References are Always Valid</h2><p>Lifetimes are Rust''s way of ensuring reference validity.</p>"},{"id":"3","title":"Traits & Generics","duration":"2 hours","content":"<h2>Zero-Cost Abstractions</h2><p>Traits are Rust''s interface mechanism.</p>"},{"id":"4","title":"Concurrency","duration":"1 hour 45 min","content":"<h2>Fearless Concurrency</h2><p>Rust''s type system prevents data races at compile time.</p>"},{"id":"5","title":"Unsafe Rust & FFI","duration":"1 hour 30 min","content":"<h2>When You Need More Control</h2><p>Unsafe Rust lets you do things the compiler can''t verify.</p>"}]'::jsonb,false) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('ai-ml-fundamentals','AI & ML Fundamentals for Engineers','Practical machine learning for software engineers.','Build and deploy machine learning models. Covers supervised learning, neural networks, LLMs, and MLOps fundamentals.','Beginner','6 hours 50 min total','Self-paced + Mentor Support','Dr. Amara Osei','Head of AI Research',ARRAY['ML Fundamentals','Neural Networks','LLMs & Prompt Engineering','Model Deployment','MLOps Basics'],5,3100,'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200','<h2>AI for Working Engineers</h2><p>This is a practical, hands-on introduction to ML for software engineers.</p>','[{"id":"1","title":"ML Fundamentals & Supervised Learning","duration":"1 hour 30 min","content":"<h2>How Machines Learn</h2><p>Supervised learning maps inputs to outputs using labelled training data.</p>"},{"id":"2","title":"Neural Networks & Deep Learning","duration":"1 hour 45 min","content":"<h2>Building Blocks of Modern AI</h2><p>From a single perceptron to multi-layer networks.</p>"},{"id":"3","title":"LLMs & Prompt Engineering","duration":"1 hour 15 min","content":"<h2>Working with Language Models</h2><p>Prompt engineering is the art of communicating with LLMs effectively.</p>"},{"id":"4","title":"Model Evaluation & Deployment","duration":"1 hour 20 min","content":"<h2>From Notebook to Production</h2><p>Deploying ML models requires more than just a trained model.</p>"},{"id":"5","title":"MLOps Fundamentals","duration":"1 hour","content":"<h2>Operationalising ML</h2><p>MLOps applies DevOps principles to machine learning.</p>"}]'::jsonb,true) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('typescript-deep-dive','TypeScript Type System Deep Dive','Master TypeScript from generics to conditional types.','Go beyond basic types. Learn advanced generics, template literal types, conditional types, and mapped types.','Advanced','7 hours 10 min total','Self-paced + Code Reviews','Thomas Ekwe','VP Engineering',ARRAY['Advanced Generics','Conditional Types','Mapped Types','Template Literals','Type Safety Patterns','Declaration Files'],5,450,'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=1200','<h2>Types That Work for You</h2><p>TypeScript''s type system is extraordinarily powerful.</p>','[{"id":"1","title":"Advanced Generics","duration":"1 hour 30 min","content":"<h2>Generic Constraints & Infer</h2><p>Learn to constrain generics with extends.</p>"},{"id":"2","title":"Conditional & Mapped Types","duration":"1 hour 45 min","content":"<h2>Types That Compute</h2><p>Conditional types are like ternary operators for types.</p>"},{"id":"3","title":"Template Literal Types","duration":"1 hour 15 min","content":"<h2>String Manipulation at the Type Level</h2><p>Template literal types let you model URL patterns as precise types.</p>"},{"id":"4","title":"Type-Safe API Patterns","duration":"1 hour 30 min","content":"<h2>End-to-End Type Safety</h2><p>Build type-safe API clients that catch mismatches at compile time.</p>"},{"id":"5","title":"Declaration Files & Module Augmentation","duration":"1 hour 10 min","content":"<h2>Extending Types</h2><p>Learn to write .d.ts files and augment third-party module types.</p>"}]'::jsonb,false) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
INSERT INTO courses (slug,title,tagline,description,level,duration,format,instructor,instructor_role,topics,lessons_count,students,image,content,lessons,featured) VALUES ('cloud-architecture','Cloud Architecture on AWS','Design resilient, cost-effective cloud infrastructure.','Learn AWS architecture from the ground up. Compute, storage, networking, security, and cost optimisation patterns.','Intermediate','7 hours 30 min total','Self-paced + Weekly Q&A','Priya Sharma','VP Cloud Engineering',ARRAY['AWS Core Services','VPC & Networking','Security & IAM','High Availability','Cost Optimisation','Infrastructure as Code'],5,1600,'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=1200','<h2>Cloud Engineering, Not Just Clicking</h2><p>This course teaches cloud architecture the right way.</p>','[{"id":"1","title":"AWS Core Services Overview","duration":"1 hour 15 min","content":"<h2>The Building Blocks</h2><p>EC2, S3, RDS, and VPC - the core AWS services.</p>"},{"id":"2","title":"VPC Design & Networking","duration":"1 hour 45 min","content":"<h2>Network Isolation the Right Way</h2><p>Designing a VPC with public and private subnets.</p>"},{"id":"3","title":"IAM & Security Best Practices","duration":"1 hour 30 min","content":"<h2>Least Privilege, Maximum Security</h2><p>IAM is the most important security control in AWS.</p>"},{"id":"4","title":"High Availability & Disaster Recovery","duration":"1 hour 30 min","content":"<h2>Designing for Failure</h2><p>Multi-AZ deployments, auto-scaling, load balancers.</p>"},{"id":"5","title":"Cost Optimisation & Infrastructure as Code","duration":"1 hour 30 min","content":"<h2>Cloud Efficiency</h2><p>Use Terraform and CloudFormation for IaC.</p>"}]'::jsonb,false) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,tagline=EXCLUDED.tagline,description=EXCLUDED.description,level=EXCLUDED.level,duration=EXCLUDED.duration,format=EXCLUDED.format,instructor=EXCLUDED.instructor,instructor_role=EXCLUDED.instructor_role,topics=EXCLUDED.topics,lessons_count=EXCLUDED.lessons_count,students=EXCLUDED.students,image=EXCLUDED.image,content=EXCLUDED.content,lessons=EXCLUDED.lessons,featured=EXCLUDED.featured;
